name: Model CI

on:
  push:
    paths:
      - 'model/**'
  pull_request:
    paths:
      - 'model/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pennylane numpy
    - name: Lint with flake8
      run: |
        flake8 model --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run quantum model examples
      run: |
        python model/quantum_model.py
