name: Model CI

on:
  push:
    paths:
      - 'model/**'
      - 'examples/**'
  pull_request:
    paths:
      - 'model/**'
      - 'examples/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8','3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pennylane numpy
    - name: Lint with flake8
      run: |
        flake8 model examples --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run quantum model examples
      run: |
        python examples/quantum_model_examples.py
